name: Infracost - Cost Estimation

on:
  workflow_dispatch:

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false  

      - name: Install Infracost
        run: |
          curl -sSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Checking cost
        run: |
          infracost configure set api_key "${{ secrets.INFRACOST_API_KEY }}"
          infracost breakdown --path .
